# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url(
        regex="^Organization/~create/$",
        view=views.OrganizationCreateView.as_view(),
        name='Organization_create',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/~delete/$",
        view=views.OrganizationDeleteView.as_view(),
        name='Organization_delete',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/$",
        view=views.OrganizationDetailView.as_view(),
        name='Organization_detail',
    ),
    url(
        regex="^Organization/(?P<pk>\d+)/~update/$",
        view=views.OrganizationUpdateView.as_view(),
        name='Organization_update',
    ),
    url(
        regex="^Organization/$",
        view=views.OrganizationListView.as_view(),
        name='Organization_list',
    ),
	url(
        regex="^Office/~create/$",
        view=views.OfficeCreateView.as_view(),
        name='Office_create',
    ),
    url(
        regex="^Office/(?P<pk>\d+)/~delete/$",
        view=views.OfficeDeleteView.as_view(),
        name='Office_delete',
    ),
    url(
        regex="^Office/(?P<pk>\d+)/$",
        view=views.OfficeDetailView.as_view(),
        name='Office_detail',
    ),
    url(
        regex="^Office/(?P<pk>\d+)/~update/$",
        view=views.OfficeUpdateView.as_view(),
        name='Office_update',
    ),
    url(
        regex="^Office/$",
        view=views.OfficeListView.as_view(),
        name='Office_list',
    ),
	url(
        regex="^Person/~create/$",
        view=views.PersonCreateView.as_view(),
        name='Person_create',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/~delete/$",
        view=views.PersonDeleteView.as_view(),
        name='Person_delete',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/$",
        view=views.PersonDetailView.as_view(),
        name='Person_detail',
    ),
    url(
        regex="^Person/(?P<pk>\d+)/~update/$",
        view=views.PersonUpdateView.as_view(),
        name='Person_update',
    ),
    url(
        regex="^Person/$",
        view=views.PersonListView.as_view(),
        name='Person_list',
    ),
	]
