# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('published_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published from')),
                ('published_to', models.DateTimeField(blank=True, null=True, verbose_name='published from')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('buildings', models.ManyToManyField(to='paorganizations.Building', verbose_name='buildingss')),
            ],
            options={
                'verbose_name': 'assignment',
                'verbose_name_plural': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('published_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published from')),
                ('published_to', models.DateTimeField(blank=True, null=True, verbose_name='published from')),
                ('address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
            options={
                'verbose_name': 'email',
                'verbose_name_plural': 'email',
            },
        ),
        migrations.CreateModel(
            name='TelephoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('published_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published from')),
                ('published_to', models.DateTimeField(blank=True, null=True, verbose_name='published from')),
                ('number', models.EmailField(blank=True, max_length=254, verbose_name='number')),
                ('type', models.CharField(choices=[('fix', 'fix'), ('internal', 'internal'), ('mobile', 'mobile'), ('fax', 'fax')], default='fix', max_length=20)),
            ],
            options={
                'verbose_name': 'telephone number',
                'verbose_name_plural': 'telephone number',
            },
        ),
        migrations.RenameField(
            model_name='person',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='office',
            name='components',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AddField(
            model_name='assignment',
            name='email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Email', verbose_name='email'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='office',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Office', verbose_name='office'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Organization', verbose_name='organization'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Person', verbose_name='person'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='telephone_numbers',
            field=models.ManyToManyField(to='paorganizations.TelephoneNumber', verbose_name='telephone numbers'),
        ),
    ]
