# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0002_auto_20170720_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='buildings',
            field=models.ManyToManyField(blank=True, to='paorganizations.Building', verbose_name='buildingss'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='telephone_numbers',
            field=models.ManyToManyField(blank=True, to='paorganizations.TelephoneNumber', verbose_name='telephone numbers'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
    ]
