# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0003_auto_20170720_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='register_number',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='register number'),
        ),
    ]
