# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0004_person_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='buildings',
            field=models.ManyToManyField(blank=True, null=True, to='paorganizations.Building', verbose_name='buildingss'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Email', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paorganizations.Office', verbose_name='office'),
        ),
    ]
