# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0005_auto_20170720_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cdr_ab_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='register number'),
        ),
    ]
