# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0007_auto_20170721_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='number',
            field=models.EmailField(blank=True, max_length=254, verbose_name='number'),
        ),
        migrations.AlterUniqueTogether(
            name='telephonenumber',
            unique_together=set([('number', 'type')]),
        ),
    ]
