# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paorganizations', '0008_auto_20170721_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephonenumber',
            name='number',
            field=models.CharField(blank=True, max_length=30, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='telephonenumber',
            name='type',
            field=models.CharField(choices=[('external', 'external'), ('internal', 'internal'), ('mobile', 'mobile'), ('fax', 'fax')], default='external', max_length=20),
        ),
    ]
